###
GET http://localhost/api_back/getuserlist/
###
POST http://localhost/api_back/

{
    "pseudo":"diokel",
    "password":"passer",
    "action":"login"
}
###
POST http://localhost/api_back/

{
    "pseudo":"tesdddt",
    "firstname":"diokel",
    "lastname":"mic",
     "password":"passer",
    "action":"register"
}

###
POST http://localhost/api_back/

{
    "expeditor":7,
    "receiver":5,
    "message":"ca va et toi",
    "action":"send message"
}
###

 

GET  http://localhost/api_back/geListMessage/5/7
