###
GET http://localhost/api_back
###
POST http://localhost/api_back/

{
    "pseudo":"test",
    "password":"passer",
    "firstname":"diokel",
    "lastname":"mic",
    "action":"login"
}
###
POST http://localhost/api_back/

{
    "pseudo":"diokel",
    "password":"passer",
    "action":"register"
}
###
POST http://localhost/api_back/

{
    "expeditor":5,
    "receiver":7,
    "message":"contenu du message",
    "action":"send message"
}
